# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13sAKZI3fOzTqyUFOsii9XlRLuet6OV-c
"""

"""
Research Library Core Utilities
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

This package provides foundational tools for managing and merging research data
for libraries across institutions. It includes utilities for:

  - Metadata parsing and validation
  - Citation generation
  - Database merging/indexing
  - Record normalization
  - (*add anything else*) <-- delete before final turn-in

  These functions serve as the basic layer toward a higher-level components and
  database integrations within a universal library system.

  Authors: ..., ..., Steven Ulloa : UMD INST326
  Version: 1.0.0
  """

from .core_functions import(
    # --- Simple Utility Functions ---
    validate_isbn,
    #..., etc, etc,

    # --- Medium Complexity Functions ---

    # --- Complex Functions ---
    merge_databases

  )

_all_ = [
    # Simple
    "validate_isbn",
    #..., ..., ..., etc.

    # Medium

    # Complex
    "merge_databases" #,
]

# Package Metadata
__version__ = "1.0.0"
__authors__ = "..., ..., Steven Ulloa : UMD INST326"
__description__ = "A foundational function library for universal research and library data management."

