# -*- coding: utf-8 -*-
"""core_functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fODuHF3g_R7DUh_WO0tuMyLg0nUyseLc
"""

import re
import json
import uuid
from datetime import datetime
from typing import List, Dict, Any, Optional

# -=-=-=-=-=-=-=-=-=-=-=-
# SIMPLE UTILITY FUNCTIONS
# =-=-=-=-=-=-=-=-=-=-=-=

def validate_isbn(isbn: str) -> bool:
    """
    Validate if the given string is a valid ISBN-10 or ISBN-13 format.

    Args:
        isbn (str): The ISBN string to validate.

    Returns:
        bool: True if valid, False otherwise.
    """
    if not isbn:
        raise TypeError("ISBN cannot be empty and must be a string.")
    isbn_clean = isbn.replace("-", "").strip()
    if len(isbn_clean) == 10 and isbn_clean[:-1].isdigit():
        return True
    if len(isbn_clean) == 13 and isbn_clean.isdigit():
        return True
    return False

# -=-=-=-=-=-=-=-=-=-=-=-
# MEDIUM UTILITY FUNCTIONS
# =-=-=-=-=-=-=-=-=-=-=-=

# -=-=-=-=-=-=-=-=-=-=-=-
# COMPLEX FUNCTIONS
# =-=-=-=-=-=-=-=-=-=-=-=

def merge_databases(local_db: List[Dict[str, Any]], remote_db: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    merge two research library databases by merging unique entries and resolving conflicts.

    Args:
        local_db (list): Local database entries.
        remote_db (list): Remote database entries.

    Returns:
        list: Merged and synchronized database.
    """
    merged = {item["identifier"]: item for item in local_db}
    for remote_item in remote_db:
        identifier = remote_item.get("identifier")
        if not identifier:
            continue
        if identifier not in merged:
            merged[identifier] = remote_item
        else:
            # Conflict resolution: prefer latest update
            local_time = merged[identifier].get("last_updated", "1970-01-01")
            remote_time = remote_item.get("last_updated", "1970-01-01")
            if remote_time > local_time:
                merged[identifier] = remote_item
    return list(merged.values())